### PR TITLE
Determine type by YT-DLP, not the URL being SoundCloud

### PR DESCRIPTION
**Pull request by upintheairsheep**

### CODE REVIEW

**Comment by vxbinaca** [comment]
Last time I ever tell you. This is the third time and the last time:

Use this:

`tubeup --metadata=collection:opensource_audio <url>`

I do not want to force audio across the board on this site. In fact I don't want to force it on the other sites it's been forced on in the past and I'm thinking of going back and undoing those options. 

Tubeup is a *quick and dirty video archival tool*. @upintheairsheep I want you to use it for video on working extractors that aren't TikTok. Or comments.

**Comment by upintheairsheep** [comment]
I am mostly using it to archive YouTube unlisted videos right now.

**Comment by vxbinaca** [comment]
Use it for that then. Why are you making broken PRs *every single day* after your break? Why are you making me review PRs to correct ONE LINE OF TYPOS IN THE README?

It's late. I'm a volunteer. I worked all day today doing physical labor. The last thing I want to do is argue with you about why you're wrong.

New rules: You get one single issue or PR a month, and the PR better not be a typo fix in the README. You're not doing that shit ever again. You're also not repeatedly making issues that have been shot down years ago from others, only to be resurrected by you. Break this and you're gone.

Do you have a bug*? You can submit multiple of those.

*A bug is not soundcloud not being made as a audio item. A bug is something that breaks Tubeup. A bug is not a typo in the README.

got it?

**Comment by vxbinaca** [comment]
@brandongalbraith Okay so I'll say it here:

1. Soundcloud sent Archive Team a cease and desist shortly after firing 60 percent of their staff and seeing Archive Team scraping as much as possible from the site (this thankfully didn't need to be done they got funding and didn't shut down). I do not need to be dealing with the possibility of a C&D.

2. This has repeatedly been asked for, I have each time given him the example command to do what he wants by modifying the metadata for the item post-download. He persists in asking for this. He wants us to do all the work for him and tailor the tool to his needs, instead of the needs of a broader audience. 

3. I was quiet about it but I just had my account suspension lifted by Archive.org for uploads. Even my reduced usage for youtube uploads is annoying them.

4. He has had account suspensions from IA and annoyed other project maintainers with his needy issues and PRs.

**Pull request closed without merging**
