### PR TITLE
fix: when uploading to archive.org, replace \n with <br>

### LINKED ISSUE #140: archive.org not handling newlines (\n) in descriptions
For example, looking at [this video](https://archive.org/details/youtube-uLALwPzJclw), by viewing the source of the description or the associated info.json, you can see that the description has newlines. These are dutifully uploaded to archive.org, but not visible on the page as presented.

Intended:
```
The Ask Project is made possible by donations from viewers like you. 
Please donate to the project at: 
* https://www.paypal.me/coreygilshuster 
* https://www.patreon.com/askproject
.
Want to know what Israelis and Palestinians in the Middle East really think about the conflict? Ask a question and I will get answers. 
```

Actual:
```
The Ask Project is made possible by donations from viewers like you. Please donate to the project at: * https://www.paypal.me/coreygilshuster * https://www.patreon.com/askproject . Want to know what Israelis and Palestinians in the Middle East really think about the conflict? Ask a question and I will get answers. 
```

----
The easiest solution to me would seem to be to replace '\n' with '\<br>' before uploading the description.
```
description_text = description_text.replace('\n', '<br>')
```

I can file a PR if you think this would work.

### PR DESCRIPTION
**Pull request by midgleyc**
Fixes #140.

While making this change, I found that a lot of unit tests currently fail (at least on my machine). I've fixed only the issues created by my change: I can file some other PRs for the others later (if I can work out why they're failing), if that would help?

### CODE REVIEW

**Comment by vxbinaca** [comment]
Yes, and please test this on a item so I can see the fixed output and I'll look over the code and merge.

If you want to fix other unit tests, go ahead and submit a PR.

**Comment by midgleyc** [comment]
Made an update to also handle Windows newlines (\r\n) as I found a video with them.

Tested on https://archive.org/details/youtube-2xjmzkjxfPo (old, with Windows newlines)
and https://archive.org/details/youtube-6FrQfONE5zk (new, Linux newlines)

**Comment by vxbinaca** [comment]
Cool so with the tags for tubeup version, Archive.org staff can run a script to fix the descriptions based on indo.json

**Comment by vxbinaca** [comment]
@midgleyc Your fix is breaking uploads with null descriptions. Please fix this or revert your PR.

**Comment by midgleyc** [comment]
Should just need a `if description_text:` before the substitution. I'll fix it.

**Comment by vxbinaca** [comment]
thank you, I don't blame you for the problem at all because seeing things like this are difficult.

**Comment by midgleyc** [comment]
PR filed as #155.

**Pull request merged**
