### PR TITLE
Fix file downloaded but not uploaded

### PR DESCRIPTION
**Pull request by refeed**
Fixes https://github.com/bibanon/tubeup/issues/61

### CODE REVIEW

**Comment by vxbinaca** [comment]
What about downloads are broken? I'll look at it in a few hours. Curious why you're pushing this.

**Comment by refeed** [comment]
@vxbinaca Could you elaborate more on "downloads that are broken" ? iirc `youtube-dl` will handle the download thingies.
Since I already write it, it's not worth to save the patch in my local computer forever :)

**Comment by refeed** [comment]
The patch that fixes #61 is actually only https://github.com/bibanon/tubeup/pull/67/commits/6015ee850fbe33a54277d33e9ee7fabd8d705772 . The other commits are some improvements in the logic related to the fix patch and some other aren't too related but worth to merge imo

**Comment by vxbinaca** [comment]
Thanks @refeed. I'd like you to take over development of Tubeup now. I can step in in an emergency and maybe make small fixes but it's basically your script now. I just tuned the item output, optimized the options for IA/YTDL and changed some dates. My opts are all that are left of the code. Everything else is yours [and so it should all be yours](https://youtu.be/cMkmGb1W-9s?t=132).

You've done well and helped people preserve history with ease, especially me.

Don't fiddle with the ytdl/IA opts they're fine the way they are. Other than that you're free to make structural changes or fixes, as long as it works I'll push it to pypi. You have write access to the repo now. She's all yours. Thank you for taking her off my hands.

**Pull request merged**
