### PR TITLE
Add physical location as a tag, if it has any

### PR DESCRIPTION
**Pull request by upintheairsheep**

### CODE REVIEW

**Comment by upintheairsheep** [comment]
Thanks for that little fix!

**Comment by vxbinaca** [comment]
I'm not against this but do we need to print "No Location found" every time? Thats going to be a lot of garbage output. Maybe just silently add it if found and if not then oh well.

**Comment by vxbinaca** [comment]
Wait is there even a output in a item for location? Or is this just journaled in metadata? Can you provide a example of a video with a location? Because if it's in JSON we don't need this PR.

**Comment by upintheairsheep** [comment]
> I'm not against this but do we need to print "No Location found" every time? Thats going to be a lot of garbage output. Maybe just silently add it if found and if not then oh well.

agree

**Comment by upintheairsheep** [comment]
> @upintheairsheep cool thought! Do you have an example video with a location attribute set?

No, however there are some extractors that use the "location" perimeter. https://github.com/ytdl-org/youtube-dl/search?q=location (yt-dlp's code is not being indexed for some reason)

**Comment by mrpapersonic** [comment]
It looks like the IA equivalent to this is the "coverage" tag:
> The extent or scope of the content of the resource (geographic place, temporal period, jurisdiction). For example, the place the work took place.

**Comment by vxbinaca** [comment]
Should we force that or can IA come back later on and pick that up like they did with subtitles? Because if and only if location metadata exists in the JSON, then let IA decide to display that by default.

Is location metadata being picked up in JSON? If not lets fix that. If it is we don't need to force it.

**Pull request closed without merging**
