### PR TITLE
Check if item exists before uploading

### LINKED ISSUE #109: Add option to skip existing items
Sometimes while processing a list of videos I'll run into the case where another archive.org user has already uploaded the same video, so tubeup will fail because I don't have permission to update the item. Unfortunately, this aborts the entire queue.

Attempting to run tubeup again with the same list, even if you exclude the problematic video, will have it redownload any videos that had already been successfully uploaded, wasting time and bandwidth.

I believe there should be flag that allows tubeup to check if an item exists before it downloads anything. As it stands, you end up having to run tubeup for each video separately.

### PR DESCRIPTION
**Pull request by mrpapersonic**
Closes #109

Example of output dialog with this patch:
```
PLT
There are no annotations to write.

** downloading stuff -- redacted **

:: Item already exists. Not uploading.
Title: PLT
Video URL: https://www.youtube.com/watch?v=uzNVWdws0jY
```

### CODE REVIEW

**Comment by vxbinaca** [comment]
Do you need to redact the output?

**Comment by vxbinaca** [comment]
Try committing with messages after successful testing in the future please. This right now is breaking all python tests.

**Comment by vxbinaca** [comment]
@antonizoon @brandongalbraith I'd like your input here if you can skim his changes that function before I consider committing this.

**Comment by vxbinaca** [comment]
Does this upload items regularly that don't exist?

**Comment by vxbinaca** [comment]
I agree, Brandon.

re: 1)

He means check for the identifier structure thats uses, so I believe thats `siteID-videoID`, if not siteID then it's extractorID.

re:2

Sometimes metadata needs to be uploaded or a partial rip fixed, which shouldn't be necessary now there's safeties Brandon implemented ages ago to prevent `.ytdl` and `.part` from uploading. Once a video or extractor and fixed the URL can be retried, likely what will happen is YT-DLP will re-try and ignore the previously downloaded stub due to codec differences when a buggy extractor is fixed.

**Comment by vxbinaca** [comment]
> @vxbinaca Haven't been getting email notifications from Github 😡 fixed!

I have them sent to a special folder in my email, and I also check Github for this project and others I follow bi-daily.

**Comment by vxbinaca** [comment]
Please test the code change before committing it I'm having to wade through a jungle of commits that breaks code. Test it on your end, commit everything in one go wholesale, then if there's linting issues do those in a second commit please. 

I literally do not understand what I'm looking at here so many things have changed over and over.

**Comment by mrpapersonic** [comment]
I have no idea why the tests are failing on Actions, they're passing on my machine.
I'm totally lost.

**Comment by vxbinaca** [comment]
You have to edit the tests with the exact same edits so they perform the same IIRC.

**Comment by upintheairsheep** [comment]
> I have no idea why the tests are failing on Actions, they're passing on my machine. I'm totally lost.

Can you also not upload if it has already been uploaded on your account?

**Comment by mrpapersonic** [comment]
> Can you also not upload if it has already been uploaded on your account?

From @brandongalbraith:
> We should check if we're the original item uploader. [...] If we _are_ the original item uploader [...] **we should throw a message out and proceed.**

Maybe this should be put into a command line option?

**Comment by vxbinaca** [comment]
Just have it check for a existing item regardless of who owns it, and allow a flag to turn that behavior off. Thats all you really need.

**Comment by vxbinaca** [comment]
Thank for the PR @mrpapersonic try to stick around in case something breaks with channel rips, but it wouldn't be a dire emergency because I could roll back to 0.00.31 for my rip server.

**Comment by vxbinaca** [comment]
@mrpapersonic How extensively did you test this? did you test it on a item you knew existed, or did you run it on a channel partially ripped to see behavior?

**Comment by vxbinaca** [comment]
Yeah we're gonna be pushing another version to fix the bugs from this feature addition

**Comment by vxbinaca** [comment]
Wait not quite. Lemme play with this new version for a day trying to stress test it.

**Comment by upintheairsheep** [comment]
> Closes #109
> 
> Example of output dialog with this patch:
> 
> ```
> PLT
> There are no annotations to write.
> 
> ** downloading stuff -- redacted **
> 
> :: Item already exists. Not uploading.
> Title: PLT
> Video URL: https://www.youtube.com/watch?v=uzNVWdws0jY
> ```

Thank you for finally fixing the single biggest issue of tubeup! Please also help me with adding tiktok comment support on yt-dlp: https://github.com/yt-dlp/yt-dlp/issues/4012

**Pull request merged**
