### PR TITLE
Add --cookies to provide cookie file to YoutubeDL

### LINKED ISSUE #161: Unable to provide cookies for youtube-dl to use
It's currently impossible to give tubeup cookies for youtube-dl to use.

As of recently, it is no longer possible to download age-restricted YouTube videos with youtube-dl without a Google account with prior age verification. The way to provide it is with a cookies file. See https://github.com/ytdl-org/youtube-dl/issues/28578
Despite the term "age-restricted", YouTube often flags perfectly fine content. I believe supporting this should be a priority.

Edit: The replies in the youtube-dl issue mention this restriction only applying to EU countries and that VPN is an option. This is no longer the case. The same can now be observed from US IP addresses. Here is such an age-restricted video: https://youtu.be/Fiu9GSOmt8E

### PR DESCRIPTION
**Pull request by XXLuigiMario**
Closes #161

### CODE REVIEW

**Comment by brandongalbraith** [comment]
@XXLuigiMario Thanks for the contribution! Have you tested this enhancement to confirm no regression (requests without a cookie file specified continue to work) and feature enhancement works as expected (retrieving an uploading a digital artifact that requires a cookies file to bypass Google's age restriction)?

**Comment by XXLuigiMario** [comment]
> 
> 
> @XXLuigiMario Thanks for the contribution! Have you tested this enhancement to confirm no regression (requests without a cookie file specified continue to work) and feature enhancement works as expected (retrieving an uploading a digital artifact that requires a cookies file to bypass Google's age restriction)?

Yes, on both counts. I made this because I ran into one of said artifacts myself, and successfully uploaded it with this patch. I've continued to upload other unrelated content without a cookie file with no issues.

**Comment by vxbinaca** [comment]
Give me 24 hours to review this, check where cookie is kept and then merge. Thanks for PR.

**Comment by vxbinaca** [comment]
New version coming soon.....

**Comment by vxbinaca** [comment]
I wanted to thank you again @XXLuigiMario for pushing this fix, even though eventually I could have hard coded tubeup to use a config for youtube-dl that pointed to a cookie this is a much more elegant solution to the ever-increasing issue of sign-in walled videos.

**Pull request merged**
