### PR TITLE
Move from travis to GitHub actions

### PR DESCRIPTION
**Pull request by midgleyc**
Sort of a continuation of #142: as travis still wasn't running, migrate to GitHub Actions instead. As part of this, fix the lint errors and the test failures.

Remove Python 3.5, as it doesn't work with internetarchiver. Add Pythons 3.8 and 3.9.

Remove the "hack to make the test in Travis successful" as the GitHub Actions test didn't require it.

### CODE REVIEW

**Comment by vxbinaca** [comment]
I need a few days to get time to look over this.

**Comment by brandongalbraith** [comment]
@vxbinaca plan to review this tomorrow 👍

**Comment by midgleyc** [comment]
@vxbinaca @brandongalbraith A couple of changes since last push, in case you started looking at it ;)

One PR introduced more flake8 errors. As part of fixing that, I just expanded the allowed line length: I don't think it's a major concern. I couldn't see a way of formatting a dict that looked better than just leaving it long.

As `master`'s gone back to using youtube-dl over youtube-dlc, I removed the commit that changed the tests to use `youtube-dlc`.

The tests run and pass on my fork: https://github.com/midgleyc/tubeup/actions.

**Comment by vxbinaca** [comment]
@antonizoon @brandongalbraith  If neither of you have problems with this I'm merging.

**Comment by brandongalbraith** [comment]
Super late response on this, sorry, life happens. Thanks @midgleyc for putting this together, thanks @vxbinaca for merging it up. Has been working great, really appreciate it. 👍

**Comment by midgleyc** [comment]
You're welcome, Brandon!

No problem, it got merged quite quickly I think.

**Pull request merged**
