### PR TITLE
Load .info.json file as UTF-8

### PR DESCRIPTION
**Pull request by mrpapersonic**

### CODE REVIEW

**Comment by brandongalbraith** [comment]
@mrpapersonic Can you provide some rough details around this PR? I can guess based on the commit, but I just want it documented here for future users and current folks who are going to cut a release when merged up to master. Thank you! 🙇

**Comment by mrpapersonic** [comment]
This PR specifies opening the .info.json file as UTF-8, as when we don't it can cause a `UnicodeDecodeError`.

**Comment by brandongalbraith** [comment]
@mrpapersonic Looks like tests are passing, can you confirm you've tested these changes with a video source that generates a .info.json file with UTF-8 content and the upload to the Internet Archive is successful?

**Comment by mrpapersonic** [comment]
Yes, I have tested uploading videos to IA, and it succeeded without errors.

**Pull request merged**
