### PR TITLE
Use 'creator' as uploader for Twitch clips

### PR DESCRIPTION
**Pull request by b-ggs**
Currently, TubeUp uses `uploader` in the ytdl metadata as the creator for IA. This becomes an issue specifically for Twitch clips, where the `uploader` is the Twitch viewer who created the clip instead of the `creator` who is the Twitch broadcaster: https://github.com/ytdl-org/youtube-dl/blob/f28f1b4d6ed053f1dbfbc7fc992162c4ea4f2ce7/youtube_dl/extractor/twitch.py#L968

Using TubeUp to archive multiple clips from the same broadcaster wouldn't get filed under the same creator. Instead it would be filed under the Twitch username of the user who created the clip. This becomes more evident when looking at the `twitchclips` collection and searching for TubeUp as the scanner: https://archive.org/details/twitchclips?and%5B%5D=scanner%3A%22TubeUp*%22&sin=

The clip I used for the unit test is the same clip ytdl uses in their Twitch clip extractor: https://github.com/ytdl-org/youtube-dl/blob/f28f1b4d6ed053f1dbfbc7fc992162c4ea4f2ce7/youtube_dl/extractor/twitch.py#L862

### CODE REVIEW

**Comment by vxbinaca** [comment]
YTDL needs to fix their extractor.

**Comment by vxbinaca** [comment]
Can you provide a example of the fix?

**Comment by brandongalbraith** [comment]
@b-ggs Tests and code looks good, can you confirm you've tested on a Twitch video uploaded by a non-creator and the creator is properly attributed in the Internet Archive item created?

**Comment by b-ggs** [comment]
I have just tested by uploading clips to IA with TubeUp comparing the current master branch vs my branch:

| Git branch | Twitch Clip URL | ytdl `uploader` (clip creator) | ytdl `creator` (broadcaster) | IA URL | IA creator |
| --- | --- | --- | --- | --- | --- |
bibanon:master | https://clips.twitch.tv/ElatedDistinctPlumYouWHY | AidenWallis | HasanAbi | https://archive.org/details/twitch-clips-796000448 | AidenWallis
b-ggs:feature/use-creator-as-uploader-for-twitch-clips | https://clips.twitch.tv/AgitatedDelightfulArmadilloWOOP | jMatrix | HasanAbi | https://archive.org/details/twitch-clips-902106752 | HasanAbi

It seems to now attribute the IA item to HasanAbi, the broadcaster, instead of the clip creator

**Comment by vxbinaca** [comment]
> It seems to now attribute the IA item to HasanAbi, the broadcaster, instead of the clip creator

That's in the JSON though. If someone creates a clip thats their thing now, not Hasans even though he's in it. Why specifically do you need this change? If it's about attrbution, it's in the metadata, just not prominentl displayed on the site.

I'm not opposed to merging this I just don't get what the issue it.

**Comment by b-ggs** [comment]
Oh! I see where you're coming from.

My intention is to make Twitch clips uploaded with TubeUp more easily searchable on the platform. Such that when people search the archive for `subject:"TwitchClips" creator:"HasanAbi"`, all the archived clips from Hasan's stream would show up similar to how clips would show up in the [Clips](https://www.twitch.tv/hasanabi/clips?filter=clips&range=7d) section of his channel, regardless of who originally clipped it.

These two clips ([1](https://archive.org/details/twitch-clips-1040030846), [2](https://archive.org/details/twitch-clips-796000448)) are both Hasan clips but I wouldn't be able to search and easily get a resultset that includes both clips since the creators are different. Likewise, there's no easy way (that I know of at least) to filter the resultset for `subject:"TwitchClips"` by broadcaster.

**Comment by vxbinaca** [comment]
Yeah so this sounds like something IA could do later based on metadata. I don't really care about SEO on the site, as long as what goes up is correct based off what the site extractors give us then this isn't a major thing.  This would be a easy thing to impliment for the too. Take X items with "twitch-vod-v*", look in JSON, see if theres a creator tag that differs from the uploader tag, if found then thats a clip that can be corrected on their end. 

This program preserves video with metadata. I personally don't like site-specific hacks for things like seachability on IA. Brandon can chime in if he wants but this is going to open the flood gates. Example, a recent issue brought up because IA was rate limited a user and he wanted to change the metadata to CSV to avoid whatever IA was doing. 

I'm not going to close the issue but I don't want to get into the habbit of merging site-specific hacks for peoples personal pet projects. I don't percieve this as missattrobution. Perhaps shoving the desired metadata element into tags would help in your searching?

But it doesn't matter the Twitch collections time is likely neigh anyway. Due to it being able to be picked up by outside search engines it's only a matter of time because that collection is de-indexed as well. Just like all Youtube uploads are hidden because of the problems it causes IA staff. Because other archivist groups don't have a sense of proportion or curation.

But muh search-ability, right?

**Comment by brandongalbraith** [comment]
Noodling on this, will get to a workstation shortly to expound on this.

**Comment by brandongalbraith** [comment]
I think there are a lot of great points around this enhancement. To @vxbinaca's point, we do want to rely on the extractor to do a lot of the heavy lifting, but on the other hand we haven't been terribly impressed with ytdl's responsiveness when we've needed issues resolved with them upstream (so, in my mind, some of these fixes are going to be required on our end in tubeup and are a necessary evil unless we're going to folk and maintain ytdl ourselves (*BIG NOPE* at this time).

I see the value in the code @b-ggs has contributed; I'll go out on a limb and say that as digital archivists we want to properly attribute content creation to the `creator` (and not whomever is doing the upload) in the Internet Archive. What account was hosting the content (`uploader`) is less important from a provenance perspective. In an ideal world, creators would be able to cryptographically sign their works so this metadata wouldn't need be retrieved and processed by this tool (and you'd be able to identify and search for their works with that crypto persona; think Keybase), but that is a long way off.

Based on this position, I vote to ship this enhancement in the short term, with the understanding I'm going to have to open an issue with ytdl to encourage improved metadata handling of creator vs uploader.

**Comment by brandongalbraith** [comment]
I've also spot checked this behavior against what we're expecting for Youtube content metadata that is provided when uploading to the Internet Archive, and the functionality matches 👍  Ship it!

**Review by brandongalbraith — APPROVED** [review]

**Comment by brandongalbraith** [comment]
@b-ggs Thank you for your contribution and the most excellent context/comments in this PR 👍

**Pull request merged**
