### PR TITLE
Avoid Uploading .part Files to IA

### PR DESCRIPTION
**Pull request by brandongalbraith**
Rough spike towards https://github.com/bibanon/tubeup/issues/153, might not work as expected.

### CODE REVIEW

**Comment by brandongalbraith** [comment]
@vxbinaca @XXLuigiMario @antonizoon 

Looking for another set of eyes on this fix. The basic premise is that immediately prior to the upload attempt for an artifact to the Internet Archive, we check if any `.part` files exist with the in-progress `videobasename`. If so, we exit (we don't want to upload incomplete files). If `tubeup` is executed again immediately after (or really, anytime in the future as long as the content is still available and the downloaded `.part` files still exist in `.tubeup/downloads/`), `youtube-dl` should successfully finish the `.part` file(s), leaving the `tubeup` process with complete digital artifacts for upload.

**Comment by vxbinaca** [comment]
Thanks Bran!

**Comment by brandongalbraith** [comment]
:+1: Full disclosure, I have not tested it extensively. Be prepared for a rollback of this piece of code if something wonky comes up.

**Comment by vxbinaca** [comment]
you've got admin so you can revert if needed. when your code is ready I'll push a new version

**Comment by brandongalbraith** [comment]
image

**Comment by vxbinaca** [comment]
Hey uh, I'm getting some videos that refuse to download all the way or merge I think it's a YTDL issue, might be bedtime for YTDL and use YTDL-P

**Comment by brandongalbraith** [comment]
@vxbinaca Drop some links in a new issue, happy to debug to see where YTDL is falling over on them.

**Pull request merged**
