### PR TITLE
Remove remaining youtube-dl and youtube-dlc references

### PR DESCRIPTION
**Pull request by upintheairsheep**

### CODE REVIEW

**Comment by vxbinaca** [comment]
@upintheairsheep I'll handle this, thanks.

**Comment by vxbinaca** [comment]
it'll get fixed another time. Enjoy the break.

**Comment by upintheairsheep** [comment]
By the way, since I have gotten banned from yt-dlp, I decided to make my own fork, https://github.com/upintheairsheep/ytdl-sheep based on ytdl-patched, a version of yt-dlp with more features you should keep an eye on.

**Comment by vxbinaca** [comment]
Cool talk to the yt-dlp guys about merging in your changes so everyone can benefit. I do not plan on re-pointing the downloader to yours unless you can maintain your fork better than they can maintain the original.

**Pull request closed without merging**
