### PR TITLE
Add client information to default metadata. Better versioning support.

### PR DESCRIPTION
**Pull request by jjjake**
The important change here is adding client information to the default archive.org metadata.

This is helpful for archive.org for knowing that an upload came from the tubeup client.

I also added better support for versioning (e.g. `tubeup --version`). Let me know if you don't like how it's implemented, and I can change or remove that.

Having the client information in the scanner field would be really helpful for us though.

Thanks, and let me know if you'd like me to make any changes!

### CODE REVIEW

**Comment by vxbinaca** [comment]
I take it part of this is to scripts can better move items around instead of relying on tags?

**Comment by brandongalbraith** [comment]
Big :+1: from me. Obviates the need for IA to be attempting to tag uploaded items as coming from tubeup after the fact, and having the version provided on demand is also helpful. Really appreciate the contribution!

**Comment by vxbinaca** [comment]
@brandongalbraith when Travis complaints are fixed go ahead and merge this. I'll push a new version to py repo tonight

**Comment by vxbinaca** [comment]
@jjjake on your end you might want to disallow uploads from clients that don't identify. This will cause great anger on my end of things from people's uploads not working but it will force a upgrade.

**Comment by vxbinaca** [comment]
I'll get to the pypi upload around 10pm eastern

**Comment by jjjake** [comment]
Thanks @vxbinaca and @brandongalbraith!

@vxbinaca keep in mind you probably wanna drop the `.dev1` from the version when you push to pypi. I wasn't sure how you guys handle versioning, so wanted to mention it incase you didn't catch it.

Thanks again, this is helpful.

**Comment by brandongalbraith** [comment]
@jjjake Thank you for merging up and the enhancements!

**Comment by vxbinaca** [comment]
Please give us 24 hours if you're going to do that forced client ID to upload thing. I have a few up loaders to warn to upgrade. Thanks. 

Feel free to merge whatever you like - I only ask if you're playing with yt-dl or ia options that you run it by us first because they're pretty good the way they are. Other than that feel free to merge your own code.

**Comment by textfiles** [comment]
There is no need to push people currently using the script into this version by us blocking them - they'll upgrade as they go. 

This was mostly motivated by the fact that a lot of metadata in mirrored videos include fund and follow links, as well as other verbiage that can seem like it's the uploader stating them, and not the original material being mirrored. This will allow us to do searches to explain a surge in uploads, or why an item was added, and so on. Plus, the "scanner:" metadata pair is the accepted field for showing scripted or procedural uploads and this falls under that.

**Comment by vxbinaca** [comment]
@textfiles I would be fine with dropping the description being printed in the items description. We have it twice, in JSON and a separate plaintext file. So if someone makes a change that does that I'll take that too.

**Comment by textfiles** [comment]
I think the item benefits greatly from having the description text in the description, including the hyperlinks. We just had a harder time noticing that the standard "Youtube Come-Ons" were an accurate part of the original and not some greedy re-skinning by an uploader. This scanner setting will be the first step in at least being easier to note. Reduction of metadata is not the answer.

**Comment by vxbinaca** [comment]
@textfiles I don't agree it's a reduction just a removal of redundancy. For example before I touched Tubeup it would put the videoID at the start of the item title.

But yeah, I can see your point the items do benefit from it.

You all are welcome to make what changes to the code you need.

Thanks Jake/Jason/Brandon.

**Comment by vxbinaca** [comment]
Pruned `dev1` branch before shipping thank you so very much gentlemen.

**Pull request merged**
