### PR TITLE
re.sub not needed per issue #88

### PR DESCRIPTION
**Pull request by altCensored**
https://github.com/bibanon/tubeup/issues/88

### CODE REVIEW

**Comment by vxbinaca** [comment]
Rip a clip from Twitch as a test to see if it uploads. Also Twitter. Verify it fixes the bug on YouTube.

**Comment by vxbinaca** [comment]
Because that code you're touching if I recall was a fix for Twitch Brandon did. I need that Twitch fix to work.

**Comment by altCensored** [comment]
oops, i now understand.
let me experiment more with this on my fork and create a pull later. am new to all this ...

**Comment by vxbinaca** [comment]
And don't forget you need to change this in the Travis.cl build as well, whatever you end up doing.

Slow down. Understand youtube-dl works with more than just YouTube. This isn't just for my projects, Archive.org staff use this.

**Comment by brandongalbraith** [comment]
See
https://github.com/bibanon/tubeup/pull/59 for context.

**Comment by vxbinaca** [comment]
Okay your bug is a edge case that might allow in rare instances, a duplicate upload.

Does this stop uploading? No.
Would your fix, more tinkering not  withstanding, stop uploads? Yes. It would break entire websites from uploading. So tread lightly.

Slow down. Test more. Look back through what we've done to see why it is the way it is.

 No worries on learning Github I learned git even more painfully than you on here.



Here's a something to look out for though: between the objects that handle YouTube-dl and internetarchive, something is going wonky and at random on channel rips  it's not uploading some videos. That's a major bug that's not been squashed.

**Comment by vxbinaca** [comment]
@altCensored I'm curious as to the rational and impact on you this bug has. How is this tossing a wrench into your gears?

**Comment by altCensored** [comment]
good question.
altCensored.com duplicates the url as it would appear on youtube, and then streams from archive.org:
https://www.altcensored.com/watch?v=-WmYKyOk44c
https://www.youtube.com/watch?v=-WmYKyOk44c

if it changes it does not work.

i did move to fast on the pulls and did not remember that the tool is not only for YT content. will move slower and test more next time :)

ps - from the https://www.altcensored.com/about/ page, it is an unbiased community catalog, please send us any channels to monitor.

**Comment by vxbinaca** [comment]
Okay don't rip them without the dash then. Also have a conversation with Archive.org staff about your project. It's neat. Give them a heads up. Remember they're a nonprofit not a mirroring service.

Learn how youtube-dl works, kinda play with it a bit. Learn how internetarchive works. See how Tubeup is used. Ask us the rationale behind why things work the way they do. And do talk with uploaders like me who tend to track channels, so you don't stomp on my efforts and fill my VPS' disk because you stomped out the item ID real estate on something I track.

Just some helpful tips from someone who's been doing this for 4 years.

**Comment by vxbinaca** [comment]
So for example Kraut and Tea. He has a collection I had staff make. That's MY collection, tracked on MY VPS, with MY scripts. I got permission FROM him in 2015. Because of my efforts his work survives.

Pop a creators name into the Archive.org search box. Not the wayback search box. Search the site to see is someone like me tracks that channel. See what's up already. Track the user down and ask them to either update the rip or to delegate responsibility to you. Because for example Lauren Southern is a fucking mess of 5 different uploaders and I had to weave in what was missed - which was like 2/3rds of her work - into something complete.

Now if I wanted to make a collection or move her work to one place I have to work with 5 people most of which are banned to get it fixed.

Talk to people.

**Comment by vxbinaca** [comment]
Is Red Ice in danger from being erased from the Internet? No just YouTube doesn't count. Take for example Forgotten Weapons. It's in 4 places. Hence why it's not in my gun content script. I only save what is in danger of really vanishing with no backups.

It's a tough call. Most of the channels on your site are on bitchute or other services already. 

Think of Archive.org as the housing of last resort.

**Comment by altCensored** [comment]
all good points, i hope to learn from the folks that have been doing it for years.
what you have done personally is amazing.

am very impressed with archive.org and sent a short email when i first created the account.

thanks for the help in general and the feedback on altCensored.com.

**Comment by vxbinaca** [comment]
Do not auto-rip Kraut And Tea, Vee or Sargon Of Akkad, they have collections that I manage and scripts automatically take care of it. When you get in a rip of a video before me I'm unable to create the item, and then I'm forced to email you to arrange a transfer into my collection. I've had to do this twice now for Sargon.

If you see me uploading it and it looks complete - like all the contents up on IA and especially of it has it's own collection like Sargon/Kraut/Vee - chances are I'm tracking it. So leave it because scripts on crontabs watch it.

I'll be back later with other things I track. I'm 3 hours late in sleep today.

**Pull request closed without merging**
