### PR TITLE
Replace IP addresses with 0.0.0.0

### PR DESCRIPTION
**Pull request by imabritishcow**
IP addresses in the info.json is now replaced with 0.0.0.0. Tested with IPv4 and IPv6.

Example
image

Test uploads
https://archive.org/download/youtube-hh82cgqftgM
https://archive.org/details/youtube-Ti-DCmmS07Q
https://archive.org/details/youtube-sKoUtJpubqc

### CODE REVIEW

**Comment by vxbinaca** [comment]
@antonizoon @brandongalbraith If neither of you have qualms about this I'm going to merge, I'm a little confused about how it finds the actual value but it does replace it.

**Comment by brandongalbraith** [comment]
@imabritishcow Would you mind adding a corresponding test for this change? You might also consider replacing the IP address with `REDACTED` instead of `0.0.0.0` so that the intent is clear.

With regards to the regex pattern, it's a bit unwieldy, but I'm happy to ship a meh solution now and a more refined solution later so that IP addresses of tubeup users isn't being committed permanently to the Internet Archive.

**Comment by imabritishcow** [comment]
I have changed it to replace with REDACTED but i'm not really sure how to create a test.

**Comment by vxbinaca** [comment]
you need to edit either the Travis.cl code or if we switch to Github tests (ahem anyone else is wanna look over that PR) it should test each PR.

**Comment by brandongalbraith** [comment]
@imabritishcow Regarding a test for this enhancement, we want to ensure we're confident we're only replacing the user's IP address by using the regex provided. Did you test the provided regex pattern on common IP address formats?

**Comment by imabritishcow** [comment]
Yes, I have tested the regex on both IPv4 and IPv6 addresses

**Comment by imabritishcow** [comment]
This isn't a great solution, i'll work on something better.

**Comment by brandongalbraith** [comment]
Appreciate it @imabritishcow 🙏.

TubeUp is executed not just from the command line, but is also baked into pipelines and other automated systems folks are running for archival purposes. Definitely want to ensure we're not munging data or erroring out unexpectedly.

**Comment by imabritishcow** [comment]
This would have removed any IP addresses in the description or title. I'm working on a solution that will edit only the formats section.

**Comment by brandongalbraith** [comment]
Good catch! We'll keep an eye out for an updated review when your new commits land.

**Comment by vxbinaca** [comment]
Yeah please be really careful with metadata. Half of the uploads from this script are automated (mostly me). I have limited mental bandwidth to vet that a change doesn't have knockon effects down the line.

I'm open to a solution but not a board one. Maybe have it look for a value in JSON and snip only that value.

**Comment by imabritishcow** [comment]
Improved IP removal and created a new test for it.

**Comment by james-jpeg** [comment]
@imabritishcow 
I just tried your regex, works fine on ipv4 addresses but it seems to fail on ipv6 addresses.

Tested this string on https://pythex.org/: 
```
FE80:0000:0000:0000:0202:B3FF:FE1E:8329
192.168.0.1
fe80:0000:0000:0000:0202:b3ff:fe1e:8329
```

Also it seems you missed a field,`requested_formats` also contains the ip address.

I think it would be better if you created a dictionary with the fields that contain an ip address which would allow us to extend it to other extractors if we needed to. 

E.g:
```
ip_fields = {
    "youtube": ["manifest_url", "fragment_base_url", "url"]
}
```

Also for the test I think it would be better to test (the whole json document) for the presence of an ip address instead of `REDACTED` this way you can fail the test if an ip address manages to slip through. 

Although compared to your old solution the new solution is quite inflexible since we have to keep track of the fields that contain an ip address. The old solution works for any website. As a fix for the old solution maybe you could create two dictionaries. One dictionary with the title, description and other fields you don't want to edit and the rest of fields in another dictionary. You run the regex on the second dictionary and then merge the two.

**Comment by imabritishcow** [comment]
The IPv6 addresses in the file are URL encoded, the regex won't match regular IPv6 addresses but it works on URL encoded IPv6 like FE80%3A0000%3A0000%3A0000%3A0202%3AB3FF%3AFE1E%3A8329

**Comment by imabritishcow** [comment]
@vxbinaca @brandongalbraith What do you think? Should I fix the old solution and use that or use the new solution?

**Comment by XXLuigiMario** [comment]
I think a better way to implement this would be to redact based on a match of the public IP address of the network. A regular expression could end up overwriting something else, and introduces a lot of complexity, especially if we want to extend it to IPv6.
We could introduce a switch like `--redact=<string>` that allows redacting of a specific substring.
In addition, we could make a request to a known service like http://ipinfo.io/json to retrieve our public IP address and redact that, I would also make this a switch.

**Comment by vxbinaca** [comment]
Why can't you just go in and post-process the JSON, strip out that or whatever other element you want?

Or, maybe use tubeup on a VPS like the README says. Or take the privacy L and accept it and run it on your desktop.

These seem to be easier solutions than this. I'll keep the issue open but this seems to be a lot of work and a lot of risk of destroying metadata than just dropping elemnets within the JSON entirely, changing behavoir/mindset or just accepting the privacy loss.

**Comment by james-jpeg** [comment]
@vxbinaca 

> If you do not feel comfortable with this, send a pull request that reliably removes both IPv6/6 addresses and the filepath, or do not use Tubeup.

The README doesn't actually tell you to use a VPS. I've personally been using a VPS but it's not straightforward because you have to mess around with the source code if the VPS doesn't have storage for the videos. I rented 100GB from digital ocean but it was mounted elsewhere so I had to change the source code to save the files in the hard drive. 

I think youtube is the only offender here. Personally I just deleted those fields that contain the ip address and moved on with my life.

@XXLuigiMario 

I don't think that's a bad idea. Though I remember in the past ipinfo restricted the amount of requests you could make. Not sure if they still do that, but something to keep in mind.

**Comment by vxbinaca** [comment]
>I rented 100GB from digital ocean but it was mounted elsewhere so I had to change the source code to save the files in the hard drive.

Digital Oceans problem. Tubeup expects `~/.tubeup/downloads` will be on the drive with actual storage space.

**Comment by toscompliantname** [comment]
>Digital Oceans problem.

ehhh

**Pull request closed without merging**
