### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by brandongalbraith**
This PR is the initial version of a bug report template for the repo's Issues. See https://github.com/bibanon/tubeup/issues/160 for genesis.

### CODE REVIEW

**Comment by brandongalbraith** [comment]
@vxbinaca Sorry for the delay! This is a first cut at an issue template for accepting bug reports. Open to comments, let me know what you think.

**Comment by vxbinaca** [comment]
Needs:

- [ ] I have fully updated `tubeup`, `youtube-dl` and `internetarchive` along with their associated dependencies.
- [ ] I am not submitting a bug report about S3 timeouts.
- [ ] I've checked the Twitter account of Internet Archive (@internetarchive) for any announced outages or planned infrastructure repairs that would affect performance of uploads.
- [ ] I have included the full un-redacted URL, properly indented full terminal terminal output from the line where the command was run to where I was returned to command prompt, and am not trying to obscure item identifiers or URLs used in the creation of the bug (we need this to recreate the bug or investigate what happened).

as conditions for submitting a bug report.

**Comment by brandongalbraith** [comment]
@vxbinaca Changes made!

**Comment by vxbinaca** [comment]
Thanks Bran!

**Comment by brandongalbraith** [comment]
New Issue experience:

https://github.com/bibanon/tubeup/issues/new/choose

image

image

Looks good! Thanks @vxbinaca!

**Comment by vxbinaca** [comment]
Looks great should really cut down on poor issues or reporting.

**Pull request merged**
