### PR TITLE
Add --get-comments option

### LINKED ISSUE #180: Add flag `--write-comments`
```
--write-comments                 Retrieve video comments to be placed in the
                                 infojson. The comments are fetched even
                                 without this option if the extraction is
                                 known to be quick (Alias: --get-comments)
```

YOutube comments are important; they show the culture of a video; it would be really nice if they are gotten. I haven't noticed the comments in info.json file.

### PR DESCRIPTION
**Pull request by johtso**
Gave it a quick test and seems to work fine.

Closes #180

### CODE REVIEW

**Comment by brandongalbraith** [comment]
Test failure in latest run is unrelated to this feature enhancement. Looks good to me 👍  @vxbinaca @antonizoon double check if there are any sticking points, otherwise let's 🚢  it!

Thank you @johtso for the effort, really appreciate it! 🙏  👏

**Comment by vxbinaca** [comment]
I'd wanna talk to the guy who runs the docker image of tubeup, but if he doesn't mind we should kill 3.7 tests and compat. My virtual appliance for achival uses 3.8 and TBH that thing could use a nuke and re-do.

**Comment by brandongalbraith** [comment]
@vxbinaca Yeah! I'm happy to drop 3.7 and and possibly compat support and add 3.10 to the test list in a separate PR. Feel free to cut one and we can tag etnguyen03 there (docker-tubeup maintainer).

**Comment by vxbinaca** [comment]
this is failing tests it only passes linting checks

**Comment by johtso** [comment]
@vxbinaca seems unrelated to these changes.

Looks like youtube may have just slightly changed what they're returning? Possibly something like this is all that's required: #195

**Review by vxbinaca — COMMENTED** [review]
looks good lets see if it passes unit tests

**Comment by brandongalbraith** [comment]
Woooooo look at those tests pass! 🚀

**Comment by vxbinaca** [comment]
Thank you everyone.

**Comment by upintheairsheep** [comment]
> Test failure in latest run is unrelated to this feature enhancement. Looks good to me 👍 @vxbinaca @antonizoon double check if there are any sticking points, otherwise let's 🚢 it!
> 
> Thank you @johtso for the effort, really appreciate it! 🙏 👏

now add
--write-auto-subs   
--write-subs 
and live chat stuff

**Comment by vxbinaca** [comment]
> > Test failure in latest run is unrelated to this feature enhancement. Looks good to me 👍 @vxbinaca @antonizoon double check if there are any sticking points, otherwise let's 🚢 it!
> > Thank you @johtso for the effort, really appreciate it! 🙏 👏
> 
> now add --write-auto-subs --write-subs and live chat stuff

Auto subs suck and aren't accurate. Theres no sense in doing a pass on a channel or video, only for YT to have had a bug or just terrible auto-subs.

We already write subs.

Livechat is implemented for Twitch but I'm unsure for YT. Throw up a PR for live subs and I'll take a look.

**Comment by Pendonym** [comment]
Was this removed?

**Comment by mrpapersonic** [comment]
> Was this removed?

yes

**Comment by Pendonym** [comment]
> > Was this removed?
> 
> yes

Why?

**Comment by mrpapersonic** [comment]
> Why?

see issue #255 and probably several others before it. There were other problems with the implementation but this was ~4 years ago and my memory is foggy.

**Comment by Pendonym** [comment]
> > Why?
> 
> see issue #255 and probably several others before it. There were other problems with the implementation but this was ~4 years ago and my memory is foggy.

Would it be possible for someone to check it again maybe yt-dlp has updated it in those 4 years?

**Comment by mrpapersonic** [comment]
None of the problems were with yt-dlp. that thread I linked contains Paul's thoughts on it and multiple reasons why it got removed.

**Comment by vxbinaca** [comment]
> > > Why?
> > 
> > 
> > see issue #255 and probably several others before it. There were other problems with the implementation but this was ~4 years ago and my memory is foggy.
> 
> Would it be possible for someone to check it again maybe yt-dlp has updated it in those 4 years?

- It's out of scope since we only focus on video, the comments are a web element not made by the creator, and even if they were theres a project called The Wayback Machine that does that better.
- Internet Archives video player can't display them and there's no feasible way for them to make to or to make use of those elements.
- It increases IP bans because you def look like a web scraper, because you for sure are now grabbing the whole page instead of doing what many do, watch the video and only the initial comment load is fetched (and discarded)
- We don't want to maintain the feature and it was causing technical problems

Edit:

It's okay to do one thing and do it well thats the Unix way anyway. Archivists curate all the time it's part of the experience of being one.

Edit 2:

I seem to remember the comments being shoved into the `.info.json` file which messes with future historians parsing of those files.

Another problem is a possible sanitization problem with the comments, say a malicious comment is posted to youtube that doesn't affect the site, but does affect a bug in a dependency IA uses when parsing that JSON en masse. I'd hate to be a vector into bad things being done to IA. A malicious comment could be crafted to do exactly this and someone runs a mirror and then waits for a bot to manage that item based on the JSON.

**Pull request merged**
