### PR TITLE
Fix Error Handling for Tags

### PR DESCRIPTION
**Pull request by brandongalbraith**
WIP for https://github.com/bibanon/tubeup/issues/121

Inspired by @antonizoon (https://github.com/antonizoon/tubeup/commit/775157ba0fabc2b4aa88de5a24e24d31bb7bd799)

### CODE REVIEW

**Comment by brandongalbraith** [comment]
@vxbinaca Additional testing is required, but I believe this PR fixes the exceptions experienced when downloading videos with empty tag metadata.

**Comment by vxbinaca** [comment]
Looking over things rn w/o testing, do null tags need a error in STDOUT? I removed the tags with VIM, processed all the files by hand. Re-ran a rip and they all uploaded.

Testing soonish. Thanks Bran.

**Comment by vxbinaca** [comment]
[Tests confirmed working](https://archive.org/download/youtube-a8ga0Labuk/-a8ga0Labuk.info.json). MErged.

I owe you a pitcher of beer. Enjoy your escape from this deteriorating world.

**Comment by brandongalbraith** [comment]
@vxbinaca Happy to help, sorry for the delay!

**Comment by vxbinaca** [comment]
@brandongalbraith you also fixed (mostly) Periscope uploads too. They died YEARS ago due to null tags. Theres another problem cropping up with about 100 or so videos but I need to investigate what the issue is, I suspect a similar one but with another keyvalue.

**Comment by brandongalbraith** [comment]
Great to hear! Feel free to create an issue with debug logs for other
failing videos and I’ll get to them when I can.

**Pull request merged**
