### PR TITLE
Update __main__.py

### PR DESCRIPTION
**Pull request by captainhook**
Utf-8 encoding of title to extend character support.

### CODE REVIEW

**Comment by vxbinaca** [comment]
Fix for travis.cl. I need to confer with a few other people to make sure this won't be a problem after testing.

**Comment by vxbinaca** [comment]
Okay sorry this took so long to merge, it's a switch in the console output on completed upload.

**Comment by vxbinaca** [comment]
I'm going to be reverting this and pushing a new Tubeup binary without your desired UTF-8 support because this in fact *breaks* UTF-8.

```
 uploading EryGv0YURRk.jpg: 100%|██████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.61MiB/s]

:: Upload Finished. Item information:
b'Title: We\xe2\x80\x99re Not Just Staying Home'
Upload URL: https://archive.org/details/youtube-EryGv0YURRk
```

My setup:

OS: Ubuntu Linux
Shell: ZSH/Byobu
Terminal emulator: Terminator set to UTF-8.

It's broken with and without Byobu. Pick a better shell and check your code better next time.

**Comment by brandongalbraith** [comment]
@captainhook Did you have an example you could provide where UTF-8 characters weren't printing to the console properly for you? If I recall, Python 3 strings default to UTF-8 so we shouldn't need to `.encode('UTF-8')`. If something is breaking, feel free to [open an issue](https://github.com/bibanon/tubeup/issues/new) and I can investigate further.

**Pull request merged**
