### PR TITLE
Adding another way to run the scripts

### PR DESCRIPTION
**Pull request by Flashfire42**

### CODE REVIEW

**Comment by vxbinaca** [comment]
I don't use windows so, how?

**Comment by antonizoon** [comment]
With Windows 10 it is possible to install Linux under it and then you have Python out of the box, which works much better. Though that's not technically Windows support.

**Comment by vxbinaca** [comment]
Native Linux is preferred.

**Comment by antonizoon** [comment]
Well, the script is going to work that way just fine. The real question is wtf causes the travis-cl build of this pull request to fail...

**Comment by vxbinaca** [comment]
Travis is wilin, bruh.

**Comment by Flashfire42** [comment]
I get that Linux is preferred but being able to run it on windows is important IMO.

**Comment by vxbinaca** [comment]
Why?

**Comment by Flashfire42** [comment]
Gives access to more people

**Comment by vxbinaca** [comment]
Did you see everyone's items got hidden? Do you know why? Because too many people use this tool. Not abuse. Use.

I'm not easing it's use. Brandon won't when he replaces me either.

Given that you want to use windows you're not following our recommendations that you use a Linux VPS. Windows isn't uniform like Linux is.

I'm not assisting people in increasing the use of this tool anymore.

**Comment by antonizoon** [comment]
I hate to say this as an open source developer who usually prides themselves on improving user interface accessibility and improving our craft for the public. 

However, it has been demonstrated by their recent announcements and mitigations that it is not in the interests of the Internet Archive to allow an ever increasing amount of people to scrape and serve publicly the endless sea of videos with their limited storage resources.

When we are able to provide alternative storage locations for this script, we will consider increasing the accessibility of the script. Because when a user is paying for the storage, they have full say over what can be stored.

**Pull request closed without merging**
