### PR TITLE
Convert script to repo.

### PR DESCRIPTION
**Pull request by jjjake**
@vxbinaca Feel free to pass on this PR, if you're not interested.

The benefit I see is that you could now register the repo on pypi, so it would be easy to install (along with all of the dependencies) via `pip install tubeup`.

A big win for us would also be that we could compile [PEX executables] (https://github.com/pantsbuild/pex). For example, try this:

```
$ curl -LOs https://archive.org/download/tubeup-pex/tubeup
$ chmod +x tubeup
$ ./tubeup -h
```

This would allow for people to simply download that file, and run the command immediately. The only dependency would be Python3, as all of the required Python libraries are packaged in the PEX file. Does that make sense?

This would be a big benefit to many archive.org users and partners who are less technically inclined. All they'd need to do is download a single file, nothing would need to be installed (granted they have Python3).

I'm happy to make any changes as well if you like the idea, but would like the repo structured differently. Just let me know. : )

### CODE REVIEW

**Comment by vxbinaca** [comment]
One question before I merge this: Will the pip version be tracked to git? I can change the README.md to instruct people to use the PIP version, but if it's manually tracked then version drift might be an issue like it occasionally does with youtube-dl. 

Not to mention the overhead and catchup I'll be doing to learn how to do this. However I don't mind doing this.

@antonizoon controls this repo. Perhaps he'd be up to the task.

**Comment by jjjake** [comment]
Thanks for following up @vxbinaca. I think we should definitely wait for @antonizoon input, thanks for letting me know they control the repo.

The pip version will only be updated when you bump the version number and run `python setup.py sdist upload` (or something similar). We could add a target to the Makefile to make pushing releases easy for you. But again, let's wait to see what @antonizoon has to say.

Please feel free to reach out to me if you have any questions, comments, or feedback that don't fit into github issues (you as well @antonizoon). My email is on my github profile.

**Comment by antonizoon** [comment]
I approve this package. Thanks for making the setup script.

**Comment by vxbinaca** [comment]
@jjjake you're good to go. Thanks again for your help it's very appreciated.

**Pull request merged**
