### PR TITLE
Abstracted item-name format into a function; fix(ing) issue when 'display_id' is null.

### PR DESCRIPTION
**Pull request by Windows81**

### CODE REVIEW

**Comment by vxbinaca** [comment]
I want you to test this PR on Twitch before you push this. You're removing a safety we inserted because Twitch has illegal characters for item names.

**Comment by vxbinaca** [comment]
@brandongalbraith mind skimming this?

@Windows81 So I have a dumb blue collar brain I'm a tradesman by profession, I have a hard time looking over commits where you add and remove code it makes my dumb tradesman mind get lost. Can you make a PR where you test your code before making the PR, and then committing to the PR in one go? I'm having trouble understanding whats going on here.

**Comment by Windows81** [comment]
Hey.  I'll get back to you on this.  I still need to familiarlise myself with CI.  I did a few things here:
1. I made a new function in `utils.py` that generates the item name (e.g. `youtube-Yc9lFIS07xU`) since that was being done in two different places.
2. I fixed an edge case I was facing with SoundCloud, where `info_dict` exists, but doesn't have a `display_id` property.

**Comment by vxbinaca** [comment]
Cool point me to the new Twitch item made using this commit branch, just make sure it works with youtube extractor and I'll merge and cut a new version

**Comment by Windows81** [comment]
Hey.  I'll have to postpone my Twitch uploads to ease the rate limit on Internet Archive's end.  I've been uploading all my songs on SoundCloud lately.

**Comment by vxbinaca** [comment]
Just one video you could make it a 20 second clip.

**Comment by Windows81** [comment]
Hey.  I've tested it on Twitch and it seems to work.  When I made the commits, I made sure that my `get_itemname` makes a sub-call `sanitize_identifier`.  Around lines 330-340, I removed the mention of `sanitize_identifier` because that would've otherwise called that function twice.

Here's the output log in non-debug mode for a ten-minute clip:
```
$ tubeup https://www.twitch.tv/videos/1849347342
Las Vegas Hotel Showcase - WIP Since March 2020 • https://www.roblox.com/games/4794911592
Unable to download video subtitles for 'rechat': HTTP Error 410: Gone
There are no annotations to write.
[download] 100.0% of        N/A at    7.00MiB/s ETA 00:00
Downloaded D:\Users\username\.tubeup\downloads\v1849347342.mp4
v1849347342: Possible MPEG-TS in MP4 container or malformed AAC timestamps
 uploading v1849347342.info.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.33MiB/s]
 uploading v1849347342.jpg: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.05MiB/s]
 uploading v1849347342.mp4: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 205/205 [03:13<00:00,  1.06MiB/s]

:: Upload Finished. Item information:
Title: Las Vegas Hotel Showcase - WIP Since March 2020 • https://www.roblox.com/games/4794911592
Item URL: https://archive.org/details/twitch-vod-v1849347342
```

**Comment by Windows81** [comment]
Update: I don't see the file on the website for some reason, despite success assurance.  Could there be another culprit to the problem?

**Comment by vxbinaca** [comment]
> The file has been encoded correctly on IA -- just took an hour and more.

Yeah things with IA sometimes take a little while. Twitch streams seem to have a lower priority.

**Comment by vxbinaca** [comment]
yeah and thanks again for the fix, hopefully we can get to a point where theres no dragons anymore

**Pull request merged**
