### PR TITLE
Add ydl option format

### PR DESCRIPTION
**Pull request by altCensored**

### CODE REVIEW

**Comment by altCensored** [comment]
ok , merging to

**Comment by vxbinaca** [comment]
why do you need this?

**Comment by vxbinaca** [comment]
Tubep asks the youtube extractor already for the best video and audio streams, even though this may induce throttling which annoys rippers. We already get the best why do you need this?

`ydl_opts['format'] = "bestvideo[height<=1280]+bestaudio"`

We already do this. Just stop playing with the opts the best have been chosen for you. It pulls top quality which is all that matters.

If you want 4k pass a cookie to tubeup of your paid Premium account. Rips shouldn't fail if they can't get 4k.

Please submit a pre-edited and tested PRs where you did the edits beforehand and did one single commit per file or layed out what you're doing.

I would *highly* recommend you not touch the opts. You'll only worsen the result.

**Comment by vxbinaca** [comment]
`ydl_opts['format'] = "b[filesize<300M] / w"`

Holy fucking shit are you European with a limited bandwidth home internet connection? You can't pay $9 or whatever for a VPS with a decent disk size over 100gb?

Absolutely not. Fork if you want this. It's best video/audio or nothing and thats not changing over my dead body.

**Comment by drzraf** [comment]
545c8fe161

**Comment by vxbinaca** [comment]
@drzraf We're willing to merge your changes if you just provide us with a example item URL from Archive.org to see if your changes work and don't break things like they did last time.

**Pull request closed without merging**
