### PR TITLE
Make Filenames Deterministic

### PR DESCRIPTION
**Pull request by brandongalbraith**
Addresses https://github.com/bibanon/tubeup/issues/73

### CODE REVIEW

**Comment by brandongalbraith** [comment]
Updating tests.

**Comment by brandongalbraith** [comment]
One test remains not passing, doesn't appear related to the work I've done and I'd rather not blindly update the test without doing additional research as to why the expected result doesn't equal the test result:

```
____________________ TubeUpTests.test_create_archive_org_metadata_from_youtubedl_meta_no_uploader _____________________

self = <tests.test_tubeup.TubeUpTests testMethod=test_create_archive_org_metadata_from_youtubedl_meta_no_uploader>

    def test_create_archive_org_metadata_from_youtubedl_meta_no_uploader(self):
        with open(get_testfile_path(
                'youtube-6iRV8liah8A.info_no_'
                'uploader.json')
        ) as f:
            vid_meta = json.load(f)
    
        result = TubeUp.create_archive_org_metadata_from_youtubedl_meta(
            vid_meta
        )
    
        expected_result = {
            'mediatype': 'movies',
            'creator': 'tubeup.py',
            'collection': 'opensource_movies',
            'title': 'Mountain 3 - Video Background HD 1080p',
            'description': ('Mountain 3 - Video Background HD 1080p\n'
                            'If you use this video please put credits to my '
                            'channel in description:\nhttps://www.youtube.com'
                            '/channel/UCWpsozCMdAnfI16rZHQ9XDg\n© Don\'t '
                            'forget to SUBSCRIBE, LIKE, COMMENT and RATE. '
                            'Hope you all enjoy! <br/><br/>Source: '
                            '<a href="https://www.youtube.com/watch?v='
                            '6iRV8liah8A">https://www.youtube.com/watch?v='
                            '6iRV8liah8A</a><br/>Uploader: <a href="http://ww'
                            'w.youtube.com/channel/UCWpsozCMdAnfI16rZHQ9XDg">'
                            'tubeup.py</a>'),
            'date': '2015-01-05',
            'year': '2015',
            'subject': ('Youtube;video;Entertainment;Video Background;Footage;'
                        'Animation;Cinema;stock video footage;Royalty '
                        'free videos;Creative Commons videos;free movies '
                        'online;youtube;HD;1080p;Amazing Nature;Mountain;'),
            'originalurl': 'https://www.youtube.com/watch?v=6iRV8liah8A',
            'licenseurl': 'https://creativecommons.org/licenses/by/3.0/'}
    
>       self.assertEqual(expected_result, result)
E       AssertionError: {'med[26 chars]r': 'tubeup.py', 'collection': 'opensource_mov[898 chars].0/'} != {'med[26 chars]r': 'http://www.youtube.com/channel/UCWpsozCMd[990 chars].0/'}
E         {'collection': 'opensource_movies',
E       -  'creator': 'tubeup.py',
E       +  'creator': 'http://www.youtube.com/channel/UCWpsozCMdAnfI16rZHQ9XDg',
E          'date': '2015-01-05',
E          'description': 'Mountain 3 - Video Background HD 1080p\n'
E                         'If you use this video please put credits to my channel in '
E                         'description:\n'
E                         'https://www.youtube.com/channel/UCWpsozCMdAnfI16rZHQ9XDg\n'
E                         "© Don't forget to SUBSCRIBE, LIKE, COMMENT and RATE. Hope you "
E                         'all enjoy! <br/><br/>Source: <a '
E                         'href="https://www.youtube.com/watch?v=6iRV8liah8A">https://www.youtube.com/watch?v=6iRV8liah8A</a><br/>Uploader: '
E                         '<a '
E       -                 'href="http://www.youtube.com/channel/UCWpsozCMdAnfI16rZHQ9XDg">tubeup.py</a>',
E       ?                                                                                     ^ ^^^
E       
E       +                 'href="http://www.youtube.com/channel/UCWpsozCMdAnfI16rZHQ9XDg">http://www.youtube.com/channel/UCWpsozCMdAnfI16rZHQ9XDg</a>',
E       ?                                                                                 ++++++++++++++    ^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^
E       
E          'licenseurl': 'https://creativecommons.org/licenses/by/3.0/',
E          'mediatype': 'movies',
E          'originalurl': 'https://www.youtube.com/watch?v=6iRV8liah8A',
E          'subject': 'Youtube;video;Entertainment;Video '
E                     'Background;Footage;Animation;Cinema;stock video footage;Royalty '
E                     'free videos;Creative Commons videos;free movies '
E                     'online;youtube;HD;1080p;Amazing Nature;Mountain;',
E          'title': 'Mountain 3 - Video Background HD 1080p',
E          'year': '2015'}

tests/test_tubeup.py:368: AssertionError
```

**Comment by vxbinaca** [comment]
It's a few PRs behind yours that did it.

**Comment by brandongalbraith** [comment]
Tests pass, ready to ship!

**Comment by vxbinaca** [comment]
Please hold back on your fix for #73 until we squash all upload bugs. Otheriwse I'm ready to merge this.

You'll have write access to the repo soon.

**Comment by brandongalbraith** [comment]
> Please hold back on your fix for #73 until we squash all upload bugs.

No worries on holding this until upload bugs are squared away.

> You'll have write access to the repo soon.

🙏 Thank you for org invite, I appreciate the appreciation! 😄 

> Also, forgive me if this is a dumb question but isn't your Twitter bug related to item descriptions and not filenames?

No dumb questions. Item descriptions not conforming to filesystem file name convention is the root cause, as the twitter description is used to build the media and meta file filenames.

> The reason being that it's filling my server with 50 videos a day not uploading and looking at the filename and picking the appropriate collection is easy (I have cludgy scripts that semi-automate this). With this change I'll have to search each videoID in a search engine and then pick the appropriate collection. SUPER labor intensive, where as this is somewhat manageable currently. Hence I wanna actually fix the upload bugs first. Once it can operate smoothly without much failure I want to do that change last. Along with date bumps and the annotations flag purge.

I am happy to contribute to improving how media is managed locally prior to IA ingestion.

> So while this fix is easy and should be done, your particular problem has to do with Twitters extractor taking the tweet and dumping it into the filename and item title.

100% correct.

**Comment by brandongalbraith** [comment]
> Just understand that other people use this tool. Scalpel not sledge hammer.

Point taken. With great power comes great responsibility!

**Comment by vxbinaca** [comment]
Take a look at our other projects, and join our Matrix server.

**Comment by brandongalbraith** [comment]
Closing this for now. While well-intentioned, I think it's preferable to retain the video title metadata in the filenames of files destined for archival. When time permits, I'll cut a new PR with twitter extraction specific logic that coerces the filenames to something more reasonable from Twitter card text.

**Pull request closed without merging**
