### PR TITLE
changed itemname to not strip leading '-' from YT video_id

### PR DESCRIPTION
**Pull request by altCensored**
per https://github.com/bibanon/tubeup/issues/88

### CODE REVIEW

**Comment by vxbinaca** [comment]
@brandongalbraith I'd like a second opinion on this. He details it in #88

**Comment by altCensored** [comment]
this is not ready, do not use.

NUFX_eC84SE was changed to NUFX-eC84SE.

am looking further ...

**Comment by altCensored** [comment]
am closing because the change breaks the code.

**Comment by brandongalbraith** [comment]
Solid effort!

**Pull request closed without merging**
