### PR TITLE
Redesign tubeup

### PR DESCRIPTION
**Pull request by refeed**
README.md: Update "Usage" section and add Travis-CI badge

    README.md: Delete all trailing whitespaces

    tubeup.TubeUp: Fix youtube-dl downloading progress bar
    
    Before this, youtube-dl downloading progress bar was not flush the line
    properly.
    
    This commit fix that problem by adding "erase to end of line" escape
    sequence to the progress bar string.
    
    And also add a newline character to a string, so that string not
    'appended' to the downloading progressbar string.

    .travis.yml: Drop test for Python 2.7
    
    Drop Travis-CI test for Python 2.7 since TubeUp just can run properly
    in Python 3.x (especially for the unicode support in Python 3.x)

    Redesign TubeUp
    
    Redesign some parts of TubeUp.
    
    - Now TubeUp can be called by other programs, since it's basically a library now.
    - Add some unittests for TubeUp, the unittests can be run by Travis-CI or local.
    - Add progress bar for uploading process by adding `verbose=True` to internetarchive
    upload method.
    - Delete `locale` feature for a while, since it's hard to do it for now.
    
    - Add `quiet_mode` argument that can be called through CLI by calling `-q` or
    `--quiet`, this argument supresses all prints to stdout and just prints the
    errors.
    - Add `--debug` argument that can be called through CLI by calling `-d` or
    `--debug`, this argument prints all log messages from the TubeUp library
    and some other libraries like internetarchive and youtube_dl, this argument
    will be helpful for debugging purposes.
    
    Some addition to CI:
    - Add flake8 test to CI, so the code must obey the PEP8 and pyflake8 rules.

### CODE REVIEW

**Comment by vxbinaca** [comment]
I haven't had a chance to test this (massive computer hardware failure at home), but why did you commit your test run on a video to the repo? That's the first question I have in what will probably be a protected back and forth on this.

**Comment by refeed** [comment]
Those files are used to be the testing fixtures that will mock `youtube-dl` in `download` and `upload` process, so the tests don't really download from the real YouTube server, instead we already provide the downloaded files from youtubedl from the prior run. https://github.com/bibanon/tubeup/pull/50/files#diff-dec14691ab9de7fa66735c7e21e1517fR33

And unit tests in this PR mostly don't require an internet connection, most of the GET and PUT requests that made by the libraries (`youtube_dl` and `internetarchive`) are mocked by making some custom responses using `requests_mock` library.

**Comment by vxbinaca** [comment]
Thank you for explaining that further for me. I can delete the files when I test this and make one change then push to PyPi. I'll do the tests later today.

Would this work if I'd previously done a rip of channels in another folder? THAT would he handy as I have numerous channels that need up be uploaded that way.

**Comment by refeed** [comment]
@vxbinaca yeah it will work if your videos were formatted with the format that is defined in https://github.com/bibanon/tubeup/pull/50/files#diff-1d913150459c248912c967aa0b93315cR169 . I think `youtube_dl` uses that format by default.

If not, we can also make a script that able to convert the filenames so youtube_dl will mark it as downloaded, or maybe just use `TubeUp.upload_ia()` manually, or create an argument that can do that thing, etc.

And FYI, by using this, the video that has been uploaded will be deleted, since `delete=True` argument is included in `item.upload()` https://github.com/bibanon/tubeup/pull/50/files#diff-1d913150459c248912c967aa0b93315cR272

BTW IMO, don't delete the testfiles, otherwise some parts of test would not work like the copy call in https://github.com/bibanon/tubeup/pull/50/files#diff-dec14691ab9de7fa66735c7e21e1517fR33 . Just send the tarball that come from executing `python setup.py sdist`, it will just include the important parts automatically.

For further packaging, I also recommend to use python wheel (https://pythonwheels.com/) , since it's faster for installation. Maybe I or someone can create a PR about that later after this merged.

**Comment by vxbinaca** [comment]
@refeed  I can process the file names easily to replace spaces with underscores. That's easy. Wouldn't I need to move them to `~/.tubeup/downloads/` though, and call each video ID for the script to pick up the local copy?

**Comment by refeed** [comment]
@vxbinaca yeah, you can do that as well

**Comment by vxbinaca** [comment]
I finally set up a python instance, and worked through my mistakes in getting it working. You got it.

**Pull request merged**
